name: Exchange App CI

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      -
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
      java-version: 1.8

    - name: Check for Lint
      run: ./gradlew ktlint --continue

    - name: Store an Ktlint Failure Reposrt
      uses: actions/upload-artifact@v1
      with:
        name: Ktlint Report
        path: app/build/reports/ktlint/index.html
      if: failure()
